### ISSUE TITLE
Not issue but asking :)

### ISSUE THREAD

**Issue by bahtiyarozdere** [macek/jquery-serialize-object#97] opened 2016-11-01 08:44 UTC
Is there an option to serialize empty values too? Thanks for great plugin 👍

**Comment by macek** [comment] 2016-11-02 23:13
Duplicate of https://github.com/macek/jquery-serialize-object/issues/38, https://github.com/macek/jquery-serialize-object/issues/80

**Closed by macek** 2016-11-02 23:13 UTC
Labels: invalid
